### ISSUE TITLE
Dont add and or remove packages abusing of the "on_modified/on_selection_modified" listener

### ISSUE THREAD

**Issue by titoBouzout** [wbond/package_control_channel#2776]
Some developers, unintentionally abuse and/or don't add correct optimizations to the usage of the "on_modified" listener, leading to a terrible user experience. 

I suggest to avoid adding these packages to this channel.

In /most cases/ abuse can be confirmed with something like this. 
- Install the proposed package.
- Open any file(this step may vary, use a file or context that trigger the listener).
- Now type and hold "a" for a moment. 
- If you see "aaaaaaaaaaaaaaaaaaaaaaa" then the package does a correct usage of the on_modified listener.
- If the view freeze with "a" then the package should not be added to the channel, and the developer should optimize the on_modified listener.

This also apply to on_selection_modified.

I believe the best way to do this, is to request a confirmation that the editor does not freeze when using this listener to the developer of the package. If the editor freeze then the developer should understand that the package is not ready for distribution.

**Comment by jbrooksuk** [comment]
This isn't the case on OSX either because of the translation popup.

![image](https://cloud.githubusercontent.com/assets/246103/7681104/c226c72a-fd64-11e4-904e-347c9d4b9700.png)

**Comment by FichteFoll** [comment]
@jbrooksuk Wrong issue?

**Comment by jbrooksuk** [comment]
@FichteFoll nope, just replying in general that holding down `a` doesn't help on OSX.

**Comment by FichteFoll** [comment]
Closing as "wontfix".
