### ISSUE TITLE
Channel Package does not point to the right branch

### ISSUE THREAD

**Issue by grundprinzip** [wbond/package_control_channel#2975]
Hi,

for my package `sublemacspro` I have the following problem. The channel entry correctly describes two different branches / settings for the two different Sublime Text versions. However, when looking at the `channel.json` provided from https://sublime.wbond.net/channel.json I see that it fetches the wrong download.

In https://github.com/wbond/package_control_channel/blob/master/repository/s.json, the entry for `sublemacspro` is like this: 

```
    {
        "details": "https://github.com/grundprinzip/sublemacspro",
        "releases": [
            {
                "sublime_text": "<3000",
                "details": "https://github.com/grundprinzip/sublemacspro/tree/release/st2/current"
            },
            {
                "sublime_text": ">=3000",
                "details": "https://github.com/grundprinzip/sublemacspro/tags"
            }
        ]
    },
```

But in the downloaded channel version it shows the entry for ST2 as:

```
{
    "sublime_text": "<3000", 
    "date": "2014-03-16 17:55:21", 
    "platforms": ["*"], 
    "version": "2014.03.16.17.55.21", 
    "url": "https://codeload.github.com/grundprinzip/sublemacspro/zip/master"
}
```

As you can see, instead of downloading the zipped package from `release/st2/current` it pulls from `master`.

We recently switched form the master branch for ST2 to a separate release branch, is it possible that while the system recognizes changes in code pushes it does not see the change in the branch? I stumbled across this issue as I was pushing code to master that was not expected to be directly delivered to the users of my package.

Thank you very much

Martin

**Comment by evandrocoan** [comment]
Should this be an issue on https://github.com/wbond/packagecontrol.io/issues?

**Comment by FichteFoll** [comment]
No, I think this is an issue with the PC package provider interface, which is also used by the website crawler.

**Comment by braver** [comment]
@FichteFoll Maybe the underlying issue hasn't actually been resolved, but since branch-based releases are considered deprecated it does look like it has become irrelevant. Agree?

**Comment by FichteFoll** [comment]
Agreed. It's been sitting idle for 6 years now, most likely because of that, so we don't need to keep track of it on the wrong repo.
