### ISSUE TITLE
sublime.wbond.net still showing my removed package

### ISSUE THREAD

**Issue by randy3k** [wbond/package_control_channel#3729]
I made a package early, but I later wanted to remove it.
https://sublime.wbond.net/packages/Simple%20Project%20Manager

That's what I have done
1) remove it from my own [packages.json](https://github.com/randy3k/sublime_packages/blob/master/packages.json)
2) remove the repo of the package

I did these several weeks ago, but I can still see my package on sublime.wbond.net

**Comment by oivva** [comment]
@wbond I [removed some packages](https://github.com/wbond/package_control_channel/pull/5717), but I can still see them on https://packagecontrol.io.
Does PC have some time limit to mark package as "removed"?

E.g. [Boxy Theme Addon - Linter Theme](https://packagecontrol.io/packages/Boxy%20Theme%20Addon%20-%20Linter%20Theme)

Thanks :wink:

**Comment by wbond** [comment]
@oivva I had that disabled for a while during an outage to prevent packages being marked incorrectly. It should be fixed now.
