### ISSUE TITLE
Require HTTPS for all repositories

### ISSUE THREAD

**Issue by wbond** [wbond/package_control_channel#3749]
In an effort to improve security, we are only going to allow repositories served over HTTPS. This requires a handful of users to move their packages.json files.

All but two repositories that are non-secure are commercial packages, so the cost of purchasing a $10 cert should hopefully not be a blocker.

Here are the users that need to provide secure URLs.

Here are the owners. I am pinging them here, and I am going to email them also.
- @spywhere, http://digitalparticle.in.th/sublime/packages.json
- @csch0, http://release.latexing.com/packages.json
- @michaelpedersen, http://release.sublimegit.net/packages.json
- @wuub, http://wuub.net/packages.json
- @borysf, http://www.sublimegerrit.com/packages.json 
- @borysf, http://www.sublimerge.com/packages.json

In addition to the packages.json files, the actual packages will need to be hosted on a secure URL also.

If you have questions, or want advice about SSL certs, hosting, etc, feel free to post here.

I'd like to get this all resolved in the next couple of weeks - so let's set a due date of November 10, 2014.

**Comment by FichteFoll** [comment]
This is now verified since a22a0946c1d30f0a0de2aedf5eee2ecb7563566b.
