### ISSUE TITLE
How to add a channel

### ISSUE THREAD

**Issue by jleeothon** [wbond/package_control_channel#3971]
I removed the default channel. Then I forked this project (no modifications), and added the URL for "channel.json" (I tried both https://github.com/jleeothon/package_control_channel/blob/master/channel.json and https://raw.githubusercontent.com/jleeothon/package_control_channel/master/channel.json). But then I try to "Install Package", it tells me there's not packages available for installation. How does it work, then?

**Comment by FichteFoll** [comment]
This should be on the package control repo: https://github.com/wbond/package_control

**Comment by jleeothon** [comment]
I'll submit the same question there, then. :grinning:
