### ISSUE TITLE
ssl-linux dependency not updated

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control_channel#4052]
@wbond, not sure if you're aware of this or if it even matters, but the ssl-linux dependency listed here is still 1.0.0 and http://packagecontrol.io/ssl-linux.sublime-package as well.

**Comment by wbond** [comment]
Yes, that URL will stay 1.0.0 for compatibility with PC 3.0.0. I am now using version-namespaced URLs for future changes: https://github.com/wbond/package_control/blob/master/bootstrap.py#L131.

I will update the `ssl-linux` dependency here. It is not really functional, but mostly so users won't be confused if they go looking for it.

**Comment by wbond** [comment]
Done
