### ISSUE TITLE
No more branch releases?

### ISSUE THREAD

**Issue by facelessuser** [wbond/package_control_channel#4072]
I am hoping to get more info on what is going to happen to existing branch based releases, and why branch based releases have been done away with.

Currently, I have many packages that have ST2 branches and ST3 branches.  It sounds like like there is a push to move devs to tag releases.  Now, I am not interested in "why" tag releases are viewed as better as I am not really arguing that; I think tag releases are good way to manage a repo.  I guess I am just curious as to the reason why devs are being pushed that way in Package Control; was it just too much to maintain?

This brings me to my next question, so how long do devs have until branches will no longer function as branches?  I guess as I am forced to to go to tag releases, I will just have to kill ST2 branches as I have no interest in ensuring future releases are backwards compatible (I do these in my free time, so I try to minimize effort for myself).  I worry about future versions of sublime as I also have no interest in supporting a combined ST3/ST4 release either.  Branches allowed for me to have legacy branches as a service for all those who haven't embraced the next version of Sublime, but really enjoy using package X.

Maybe there is a way to limit certain versions of ST to specific tag ranges?  In my case I am not sure how I am going to create a tag for ST2 users and then create tags exclusively for ST3 users in order to move my branches to a tag system.   Currently, the only way I see is to kill ST2 support for all of my plugins.  I guess I leave a branch that users manually install, but that kind of sucks for those who have invested in the Package Control environment.

**Comment by facelessuser** [comment]
Looks like I may have answered one my questions reading over the example json:

```
// If your package is only compatible with specific builds of
		// Sublime Text, this will cause the package to be hidden from
		// users with incompatible versions.
		//
		// The "tags" key can be true for all valid semantic version tags, or
		// can be a prefix string. Only tags in the form
		// {prefix}{semantic_version} will be selected. In the example below,
		// the entry with "sublime_text": "<3000" will match tags like:
		//
		// "st2-1.0.0"
		// "st2-1.1.0"
		//
		// The release with "sublime_text": ">=3000" will match tags like:
		//
		// "st3-1.0.0"
		// "st3-1.1.0"
		{
			"details": "https://github.com/wbond/sublime_alignment",
			"releases": [
				{
					"sublime_text": "<3000",
					"tags": "st2-"
				}
				{
					"sublime_text": ">=3000",
					"tags": "st3-"
				}
			]
		},
```

I guess with knowing that I could release specific tags, the why isn't nearly as important.

So I guess that just leaves me with how long do devs have to migrate to this system?

**Comment by facelessuser** [comment]
This doesn't look like it will take much to migrate to the new system.  I won't worry too much about the deadline.  It looks like I will probably be able to migrate without much effort.  I will go ahead and close ths.

**Comment by wbond** [comment]
Branch-based releases prevent a number of features from being available, such a pre-releases, and the ability to pin versions (which I am hoping to add in the future).

As you found in the docs, I think I devised a way that should be pretty painless to use tags. If you have suggestions about improvements, I'd be happy to hear.

**Comment by facelessuser** [comment]
> Branch-based releases prevent a number of features from being available, such a pre-releases, and the ability to pin versions (which I am hoping to add in the future).

Sounds good.

> As you found in the docs, I think I devised a way that should be pretty painless to use tags. If you have suggestions about improvements, I'd be happy to hear.

This is fine, the more I read, the more I like this approach.  It allows for a more sane approach to releasing packages, but still allows you to release form different branches.  I probably should have done some more reading first.  My main concern was distributing releases for ST2 and ST3 separately.  I didn't want to cut off the ST2 users, but I simply don't have time to support ST2 and ST3 branches.  But as I found, you covered that nicely.

I like this, and will be migrating.  Thanks for all the hard work!
