### ISSUE TITLE
Question about ChannelRepositoryTools: Test Default Channel

### ISSUE THREAD

**Issue by psalaets** [wbond/package_control_channel#4080]
I'm running `ChannelRepositoryTools: Test Default Channel` as instructed in step 7 of [Submitting a Package](https://packagecontrol.io/docs/submitting_a_package) guide. In ST2 5048/5078 tests fail. In ST3 they all pass.

Most failures have a reason of

```
AttributeError: 'DefaultRepositoryTests' object has no attribute 'assertIn'
```

which seems like some assertion API is assumed to be available but isn't.

Are these failures expected in ST2?

**Comment by FichteFoll** [comment]
Could you perhaps include a line number for that exception?

**Comment by FichteFoll** [comment]
The thing is, this method is used thorough the entire tests and was added only in 2.7, like many other methods from `unittest`. I thought that @wbond made the tests compatible with ST2 a while ago (and assumed they worked somehow), but it seems they actually didn't.

@wbond, we have two options now. 1) Rewrite the tests to not use these methods, or 2) use the `unittest2` module. Maybe through the new dependency management?

**Comment by wbond** [comment]
The tests definitely did work in ST2, and I will fix it so they do again. There is a compatibility shim for 2.6 in there.

**Comment by psalaets** [comment]
Full output for one of the failures:

```
ERROR: test_dependency(u'./repository/dependencies.json', {u'name': u'pyyaml', u'releases': [{u'base': u'https://github.com/packagecontrol/pyyaml', u'sublime_text': u'*', u'tags': True}], u'author': u'FichteFoll', u'load_order': u'50', u'issues': u'https://github.com/packagecontrol/pyyaml/issues', u'description': u'Python PyYAML module'}) (package_control_channel.tests.test.DefaultRepositoryTests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "./tests/test.py", line 85, in wrapper
      return method(self, *params)
    File "./tests/test.py", line 266, in _test_dependency
      self.assertIn(k, self.dependency_key_types_map)
  AttributeError: 'DefaultRepositoryTests' object has no attribute 'assertIn'
```

this is in ST 2.0.2 build 2221 on OSX 10.10.2

**Comment by wbond** [comment]
Fixed in 0786c8e74325e90054cfb123c7152412a23109fb. It seems @FichteFoll had deleted the compat import back in December (71f32a7f91122975cee199d1eb44e86f2365949a).

**Comment by psalaets** [comment]
Thanks for the quick responses.

How do I get this fix? I've tried

- restarting sublime
- reinstalling ChannelRepositoryTools
- removing and re-adding the default channel (https://packagecontrol.io/channel_v3.json)
- reinstalling Package Control

I'm getting the same test failures. Line numbers in stacktraces are off by 1 compared to the latest tests/test.py. Is there a cache I need to blow away?

**Comment by FichteFoll** [comment]
You need to rebase (or merge) your package_control_channel fork onto upstream/master.
