### ISSUE TITLE
How to update a package description?

### ISSUE THREAD

**Issue by tadast** [wbond/package_control_channel#4112]
I own [a package](https://packagecontrol.io/packages/Ruby%20on%20Rails%20snippets) and the description is out of date (it says "Rails 3, Ruby 1.9 oriented snippets"). I guess it was fetched from the GH page description field, which has changed since https://github.com/tadast/sublime-rails-snippets.

Should this update automatically or do I need to do anything manually?

**Comment by wbond** [comment]
Yes, it updates automatically once an hour. Looks like it is all set now.
