### ISSUE TITLE
Oceanic Next Color Sceme is removed from packages

### ISSUE THREAD

**Issue by voronianski** [wbond/package_control_channel#4508]
I've renamed my repo on github and submitted PR which was merged - https://github.com/wbond/package_control_channel/pull/4507

However `Oceanic Next` is no longer searchable on package control and its' page states it is removed - https://packagecontrol.io/packages/Oceanic%20Next%20Color%20Scheme

<img src="https://dl.dropboxusercontent.com/u/100463011/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-06-12%20%D0%B2%2017.45.40.png" width="500" />

**Comment by FichteFoll** [comment]
That's because the url is incorrect. If you check https://github.com/wbond/package_control_channel/pull/4507/files, you can see that it's pointing to ...oceanic-next-color-theme but it should be ...-scheme.

**Comment by voronianski** [comment]
@FichteFoll sorry.. missed concentration a bit.

**Comment by voronianski** [comment]
Could you merge https://github.com/wbond/package_control_channel/pull/4511 to fix this?

**Comment by voronianski** [comment]
@FichteFoll thanks!
