### ISSUE TITLE
install messages and package's default settings is not shown

### ISSUE THREAD

**Issue by houcheng** [wbond/package_control_channel#4991]
Hi, I am author of filefinder plugin, I found my plugin and several plugins has the same issues: 1) the install message is not shown and 2) the default setting is empty.

tests my sublime 3 on ubuntu environment:
- ctags plugin: only (1) issue
- TossFile and Filefinder plugin: (1) and (2) issue both happen

**Comment by FichteFoll** [comment]
1. Your `messages.json` is invalid JSON. (hint: comma)
2. Your package is installed as "FileFinder", while in your `Main.sublime-menu` file you specify the path as "Filefinder". Case sensitivity matters on non-Windows OSes.

**Comment by houcheng** [comment]
Got it, I'll fixed these soon. 
Thanks a lot,

**Comment by houcheng** [comment]
Hi FichteFoll,
I've fixed issues and my package is upgraded to tag 1.6.0.
Will this version be automatically detected by package control ?

**Comment by FichteFoll** [comment]
Yes.
