### ISSUE TITLE
WakaTime package mysteriously removed

### ISSUE THREAD

**Issue by alanhamlett** [wbond/package_control_channel#5090]
The WakaTime package is listed, but for some reason it's shown as `removed` on the website and inside Sublime Text.

How can we get it enabled again?

<img width="1215" alt="screen shot 2016-01-01 at 10 40 03 pm" src="https://cloud.githubusercontent.com/assets/522344/12073568/eb845cea-b0d8-11e5-855b-c0bead5ede0b.png">

https://github.com/wbond/package_control_channel/blob/d16b244c15869a844e4768213c693ad1402f2712/repository/w.json#L27

**Comment by alanhamlett** [comment]
Nevermind, it seems to be enabled again. Any idea what could have caused this?

**Comment by FichteFoll** [comment]
Must likely the server outage caused by ddos on the hosting network.
