### ISSUE TITLE
Problem: packagecontrol.io

### ISSUE THREAD

**Issue by marrokin** [wbond/package_control_channel#5091]
Buenas Tardes,
Al parecer no se puede descargar nada de packagecontrol.con todos los plugins aparecen removidos
http://prntscr.com/9ledu9

**Comment by FichteFoll** [comment]
We only understand English.

That said, the website is undergoing heavy hosting issues because inode at Atlanta has been suffering from DDoS attacks for two days. Your reported issue will very likely resolve itself once the servers are running smoothly again.
