### ISSUE TITLE
Package removed with no reason

### ISSUE THREAD

**Issue by equinusocio** [wbond/package_control_channel#5096]
Hi, i see that my most popular package was removed from package control as the relative page says

https://packagecontrol.io/packages/Material%20Theme

why this? i've made no change to the master branch and the latest release. i've checked your channel repository and the package still there. What's wrong? i have no idea how to fix this.

**Comment by princemaple** [comment]
It's not being displayed as removed now. It was probably because of [this DDoS attack](https://twitter.com/wbond/status/683776623880093696), if PackageControl was hosted on Linode.

**Comment by princemaple** [comment]
https://github.com/wbond/package_control/issues/1057

**Comment by equinusocio** [comment]
thanks. So we have to wait.
