### ISSUE TITLE
Package is missing due to SSL expiration.

### ISSUE THREAD

**Issue by markdleblanc** [wbond/package_control_channel#5104]
I let one of the channel's SSL certificate expire for approximately 1 week prior to renewing it, this was in December. The package referenced is still 'missing', just curious if there is anything I can do to have it show up, or if I simply have to wait longer?

https://eberstarkgroup.com/releases/packages.json

The package in question: SyncR (https://packagecontrol.io/packages/SyncR)

**Comment by wbond** [comment]
From mousing over the Missing message, it appears that for some reason Python's ssl module on Ubuntu 12.04 doesn't like the cross-signed Let's Encrypt root. I'll have to look into the OS trust store to see if it is missing from, or just not present on Ubuntu 12.04.

**Comment by wbond** [comment]
This domain seems offline now.
