### ISSUE TITLE
Weave - Package Not Listed

### ISSUE THREAD

**Issue by mailtoharshit** [wbond/package_control_channel#5123]
@FichteFoll  - Just wondering what I cannot pull up 'Weave' Package on https://packagecontrol.io/ (search) and through sublime as well though it is listed in JSON (w.json) master package?

**Comment by FichteFoll** [comment]
Sorry, I missed a step in the review.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by princemaple** [comment]
@FichteFoll a review bot / script :)

**Comment by FichteFoll** [comment]
We do have tests on the channel already, but there are many more things that are quit hard to check automatically. Checking for a correctly-formatted tag would be possible, but the script has to know the repo it needs to check.

The best would be if we somehow made additions, deletions or changes to the channel completely moderated by a tool (comparable to `apm`), but that has to be written first.

**Comment by princemaple** [comment]
@FichteFoll my original idea was to setup a server that takes PR webhooks, process the PR and comment on the PR. However, after a second thought, an additional server means additional cost. Now that heroku forces free dynos to sleep 6hrs per day, I don't know any other ways to host a dynamic server for free.

The free travis test service seems to be the only viable way then.
A github api key can be encrypted and stored in the `.travis.yml` file. The test script can be updated to make api calls to process + comment the PR. The test script probably doesn't have the knowledge about the PR :( I know travis can do webhooks, one way or another, but not sure if you can actually make api calls in test scripts.

**Comment by FichteFoll** [comment]
We're already using travis for the json data and I'm sure we could also perform github api calls there (without releasing our key), but the hard part is finding out the repo that was added (and if it was "added" at all and not just moved around or something). Applying code analysis on pull requests is just too arbitrary to make it bullet-proof and not fail miserably in some cases.

Ultimately, we need to move away from pull request onto a repository of JSON files and only provide an interface to the default channel that has predictable results, e.g. a package manager with a few tasks like `apm`/`npm`. Only then we can truly expand tests and have automation in a reliable way.

But this really should be in its own issue.

**Comment by princemaple** [comment]
:+1:

**Comment by mailtoharshit** [comment]
@FichteFoll Added Tagging

**Comment by mailtoharshit** [comment]
https://packagecontrol.io/packages/Weave
