### ISSUE TITLE
bug of tests: sublime_text must be `*` or of the form <relation><version>

### ISSUE THREAD

**Issue by randy3k** [wbond/package_control_channel#5280]
When I run the test, I got,

>  AssertionError: sublime_text must be `*` or of the form <relation><version> where <relation> is one of {<, <=, >, >=} and <version> is a 4 digit number: '^(\\*|<=?\\d{4}|>=?\\d{4})$' not found in '3000 - 3102'

I believe that `3000 - 3102` is a [valid](https://github.com/wbond/package_control/blob/5643f4fa9a335a4591482a8ecdf6e0d7413fbaa1/package_control/providers/release_selector.py#L70) option for `sublime_text`, but the [test](https://github.com/wbond/package_control_channel/blob/3bb52b46e4ae13e08e7f0189aff0fc1c850f1a67/tests/test.py#L479) fails to reflect this.

The fix should be easy, but I won't have time until the coming weekend.

**Comment by FichteFoll** [comment]
Agreed.

I also expected this topic to come up with the big change of new new syntax format which would likely be the first actual use case where it would matter. I'll fix it shortly.

**Comment by FichteFoll** [comment]
Fixed via 8e31dc9c1a83ea746ffae5534e3c65e77b0496a9.

**Comment by randy3k** [comment]
The new syntax format is the exactly reason I did this. Thanks for the quick fix.
