### ISSUE TITLE
Package is not updated

### ISSUE THREAD

**Issue by gepd** [wbond/package_control_channel#5283]
Yesterday I've pushed a new version of my package to github, but in the package control it's not updated yet, there is an extra step after release a new version? I've searching in the [documentation](https://packagecontrol.io/docs) of the site and I haven't found anything related about my doubt. 

Doing some research in the pass issues, some people asked the same but never took so long.

What is the estimated time to wait until the package could be updated? If it's not updated what are the steps to follow?

The package is https://packagecontrol.io/packages/Deviot (the new version is 1.1.0)

Would be good the add this info in the documentation.

**Comment by randy3k** [comment]
From my past experiences, the server usually cache the updates every few hours. I guess currently the server has a problem in caching package updates. See the list of [updated packages](https://packagecontrol.io/browse/updated), the most recent update was already two days ago. And there are obviously new/updated packages published. We just have to wait patiently...

**Comment by gepd** [comment]
Thanks @randy3k 
I'm new using the package control as developer and I didn't note that section with the last updates, It's a good place to check. I had read some post saying that the updates took effect in few hours, but my concern was if I had done something wrong.

Your information was really useful

**Comment by FichteFoll** [comment]
Might still be worth poking @wbond about this~

**Comment by FichteFoll** [comment]
Seems like it has been resolved.

**Comment by randy3k** [comment]
Not really, I have update several packages the past few days, only one of them has shown up.

**Comment by wbond** [comment]
No, it has not been resolved. One of the commits within the past few days is breaking the crawler, but I have not had time to finish debugging it yet.

**Comment by FichteFoll** [comment]
Ah, okay. I just noticed that the latest package update has been '9 hours ago' and assumed it would be working then.

Anyway, my job here is done~

**Comment by gepd** [comment]
Thanks for the the clarification @wbond
