### ISSUE TITLE
Can't find package, but repo in list

### ISSUE THREAD

**Issue by Talkerbox** [wbond/package_control_channel#5519]
I can't find Find Yaml Anchor on packagecontrol.io, but this repo in list:
`{
	"name": "Find Yaml Anchor",
	"details": "https://bitbucket.org/talkerbox/findyamlanchor",
	"releases": [
		{
			"sublime_text": "*",
			"tags": true
		}
	]
},`

Something wrong?

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by Talkerbox** [comment]
Oh, thanks! I fixed it. When the changes will applied?

**Comment by AvitanI** [comment]
I have the same problem too but even when released version 'v1.0.0'  on github i d'ont see any changes. Can you help me please?
[https://github.com/doobleweb/ToolTip-Helper]

**Comment by FichteFoll** [comment]
@Avitanl, looks fine here https://packagecontrol.io/packages/ToolTip-Helper. Remember that PC does not list a package for installation if you have it already.
