### ISSUE TITLE
Why package marked missing

### ISSUE THREAD

**Issue by rexdf** [wbond/package_control_channel#5543]
https://packagecontrol.io/packages/ChineseLocalization

I updated a new version and packgecontrol is missing.

**Comment by rexdf** [comment]
Is an issue of packagecontrol server or github or missing infomation in message.json?

**Comment by FichteFoll** [comment]
Everything looks alright from the outside. @wbond will need to step in here.

**Comment by rexdf** [comment]
Why do it take so long?  I begin to take a look at https://github.com/wbond/packagecontrol.io

**Comment by rexdf** [comment]
I will make it private for a while.

**Comment by rexdf** [comment]
memory leak or insufficient memory
packagecontrol.io server

**Comment by facelessuser** [comment]
I'm seeing this too.

**Comment by facelessuser** [comment]
FYI, the plugin missing in action is BracketHighlighter.

**Comment by Kozuno** [comment]
Hello, I don't understand how to rename ChineseLocalization to make BracketHighlighter install available again in package control.
Package control works great when I install it but I don't see BracketHighlighter listed in package control & my attempts to install it manually failed. I also tried to reinstall ST deleting ~/.config/sublime-text-3 folder but problem remains, I can't use this great plugin again :(
Please h3lp 4 816 n008 :v

**Comment by facelessuser** [comment]
This is the same issue, but renaming ChineseLocalization won't help BracketHighlighter.  If I renamed BracketHighlighter in Package Control it might help it show up again, but I don't want to rename my package, and that is a hack to get it to come back.  Unless someone can tell me I've done something wrong, I think Package Control should fix this.

**Comment by Kozuno** [comment]
@facelessuser Thank you for the feedback, I really appreciate. Let's hope Package Control will fix this integration problem, because honestly your package is really awesome to read more easily a code and I am not sure if I would like to stay on ST without this great utility. Sometimes I am really lame to find where brackets begin and BracketsHighlighter helps a lot. Probably one of the best package to me on ST, so congratulations for the code !

**Comment by facelessuser** [comment]
@Kozuno, thanks!  You should be able to install the package manually as outlined here https://github.com/facelessuser/BracketHighlighter/issues/351#issuecomment-228601428.  Alternatively you can use git which I don't cover as not everyone is comfortable with git or has it installed on their machine.  You still need Package Control to install the dependencies though, but that is covered in the linked post.

**Comment by rexdf** [comment]
I tried all kind of ways. 

The actual working one is to delete tags. If the number of tags exceeds a threshold, packagecontrol.io will cannot see it.

**Comment by facelessuser** [comment]
Ahhh.  Maybe I can delete some old ones as a temporary solution.

**Comment by rexdf** [comment]
I used to rename the old repo  and create a new temporary repo with the name in packagecontrol.  If the new repo had just one release, Package Control will find it.

**Comment by facelessuser** [comment]
Ideally it will be fixed moving forward, but I don't mind deleting some really old tags just to get this going again.  It would be annoying to have to create new repos over and over again.

**Comment by rexdf** [comment]
Yep, stars and forks  and pulls will be broken.  

I think that packagecontrol use releases tags but not tags. see https://developer.github.com/v3/repos/releases/ and https://developer.github.com/v3/repos/#list-tags

**Comment by facelessuser** [comment]
What's the difference?  Wouldn't they run into the same issue when there are too many releases, or would that not be an issue?

**Comment by facelessuser** [comment]
Hmm.  I think I was removing release tags and not normal tags...

**Comment by rexdf** [comment]
I don't know the real bug behind pc, maybe github have some limit like X-RateLimit-Remaining.

```
GET /repos/:owner/:repo/releases
Status: 200 OK
Link: <https://api.github.com/resource?page=2>; rel="next",
      <https://api.github.com/resource?page=5>; rel="last"
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4999
```

**Comment by facelessuser** [comment]
Maybe, but you were correct.  I just deleted some tags, and now BracketHighlighter is back.  At least @wbond can at least know what causes the issue now.

**Comment by facelessuser** [comment]
I wonder if this was brought on because package control had to search for old ST2 releases as I have tags for both.  I imagine it would have found the recent ST3 release quickly, but since the ST2 release was at the bottom of the stack, main that was part of the issue.

**Comment by rexdf** [comment]
Not sure about it. But I have tags for both too. 

https://github.com/wbond/packagecontrol.io/blob/master/app/lib/package_control/clients/github_client.py#L96-L112

**Comment by Kozuno** [comment]
Yes this is strange, maybe it was an issue between tags and ST3 last update. Thanks a lot for your help and having found a way to make it re-available in Package control, and also for your alternative solution. Your package really adds a huge difference in code readability in ST, so big respect for the great work & idea. I am glad to be able to use it back again !

**Comment by FichteFoll** [comment]
PC needs to scan all tags in order to find the appropriate one for a release channel. It also started exposing all tags of a package/release in the default channel at some point in the past, although that information is seldomly used or not at all.
