### ISSUE TITLE
Package missing from default channel

### ISSUE THREAD

**Issue by nholmber** [wbond/package_control_channel#5560]
My package [cp2k-syntax](https://github.com/nholmber/cp2k-syntax) was recently added to the Package Control repository file [c.json](https://github.com/wbond/package_control_channel/blob/master/repository/c.json). However, for some reason the package is not visible in the default channel [https://packagecontrol.io/channel_v3.json](https://packagecontrol.io/channel_v3.json) and therefore cannot be installed through Package Control.

Any idea what is going on? I fixed the versioning issue that was mentioned in my [pull request](https://github.com/wbond/package_control_channel/pull/5544)

**Comment by FichteFoll** [comment]
You specify a `st3-` prefix for tags in your configuration, but don't define any tag with that. Either push a tag named `st3-1.0.0` or change the prefix to `true`, which is the default and recognizes both `v` and no prefix.
