### ISSUE TITLE
First «Create pull», then «Title»

### ISSUE THREAD

**Issue by Kristinita** [wbond/package_control_channel#5724]
Docs page «[Submitting a Package](https://packagecontrol.io/docs/submitting_a_package#Step_8)»:

+ 3. Enter a description in the `Title` field
+ 4. Click the `Create pull` request button 

But on the third step of nowhere `Title` field.

![No Title Field](http://i.imgur.com/XtQhoFH.png)

Likely it is necessary to trade places the third and fourth points.

Thanks.

**Comment by FichteFoll** [comment]
Please open this issue at http://github.com/wbond/packagecontrol.io.
