### ISSUE TITLE
Pages not removed after deleting a package.

### ISSUE THREAD

**Issue by titoBouzout** [wbond/package_control_channel#5815]
Hi there, so it seems finally the packages been removed from the channel, but the pages are still showing, could be possible to invalidate or remove the following:

https://packagecontrol.io/browse/authors/titoBouzout
https://packagecontrol.io/packages/SideBarEnhancements.

etc

**Comment by FichteFoll** [comment]
https://github.com/wbond/packagecontrol.io

I also highly doubt this will happen since it erases information that can still be useful, e.g. when trying to find out why you can't find a certain packaghe anymore.

**Comment by BLUDNICK** [comment]
Hi.
I'm sorry but why can not I download plug-ins:
Tag
EncodingHelper
SideBarEnhancements
BooferScroll
WordCount
?!
:-(

**Comment by FichteFoll** [comment]
>the packages been removed from the channel

by the author himself

**Comment by BLUDNICK** [comment]
It's a pity!
Tell me please... I have installed these plugins on another computer. I can copy them.. And how to do it correctly?

**Comment by FichteFoll** [comment]
Yes, you can copy them.
