### ISSUE TITLE
Images in readme are broken

### ISSUE THREAD

**Issue by DinkDonk** [wbond/package_control_channel#6113]
The images in the readme appears to be broken.
Example of issue:

[DinkDonk Color Scheme](https://packagecontrol.io/packages/DinkDonk%20Color%20Scheme)

Images in this particular package are PNG's.

**Comment by wbond** [comment]
Pasting the URLs into a browser returns an HTML page, so it appears the markup is broken.

**Comment by DinkDonk** [comment]
Thank you for getting me on the right track!  
I wasn't aware that github's raw links actually had some secret sauce causing them to be interpreted differently depending on where the URL is used.

I put the images in question in a `gh-pages` branch and it works a treat now 😄
