### ISSUE TITLE
Packages.json with URL and Tag release?

### ISSUE THREAD

**Issue by thinkv** [wbond/package_control_channel#6336]
Hi team,

Is it possible to have repository with a packages.json that contains both URL releases (for older versions), and then a maintained channel release with tagged versions?

eg. https://github.com/thinkv/sublime-elfinder/blob/5a11b901f180aa360bf477753813d36ee11aa829/packages.json

**Comment by FichteFoll** [comment]
Take a look at this PR and the tags on that repo: https://github.com/wbond/package_control_channel/pull/6316

**Comment by thinkv** [comment]
Ah thank you, I must have read it wrong, I have updated it now with date fields.

The reason I am not using the default channel is because the older versions are pointing to the URL releases from the previous owner. And version 3 and up is now on my repo. 
https://github.com/thinkv/sublime-elfinder/blob/master/packages.json

**Comment by FichteFoll** [comment]
```
Running Remote Repository Tests

  Downloading https://github.com/thinkv/sublime-elfinder/raw/master/packages.json ... done
  
  ....
  ----------------------------------------------------------------------
  Ran 4 tests in 0.003s
  
  OK
```

Looks good.
