### ISSUE TITLE
README screeen shots broken in package control decription

### ISSUE THREAD

**Issue by bijoythomas** [wbond/package_control_channel#6458]
Minor issue but is there a reason why the screen shots referenced in the readme here: https://github.com/bijoythomas/sublime-jsscratchpad seems to be broken links here: https://packagecontrol.io/packages/JavaScript%20Scratch%20Pad ?

Is there a specific markdown that makes them appear correctly?

**Comment by wbond** [comment]
Seem to be working properly to me. Perhaps you saw it while the crawler was downloading the images?

**Comment by wbond** [comment]
In the future, bugs with the website can be filed at https://github.com/wbond/packagecontrol.io/issues.
