### ISSUE TITLE
Removed packages still appear on packagecontrol.io

### ISSUE THREAD

**Issue by TobyGiacometti** [wbond/package_control_channel#6494]
After my pull request #6493 for removal of a package was accepted, I noticed that the package still appeared on packagecontrol.io. To make sure that this was not just the case with my package, I checked whether other removed packages still appear: they do. For example, the package removed in commit ca25f8e6b25d3c60c7c706f7ae590ca95c0baac7 one month ago still appears on packagecontrol.io.

**Comment by FichteFoll** [comment]
Seems to be the same for https://packagecontrol.io/packages/Theme%20-%20Retina, removed in #6423.

**Comment by evandrocoan** [comment]
@TobyGiacometti, perhaps this is an issue for https://github.com/wbond/packagecontrol.io/issues?

**Comment by FichteFoll** [comment]
Indeed. Closing this here.

**Comment by TobyGiacometti** [comment]
Yes, might be better there. In fact, an issue for this already exists: https://github.com/wbond/packagecontrol.io/issues/86
