### ISSUE TITLE
Question: Monorepo support?

### ISSUE THREAD

**Issue by JamieMason** [wbond/package_control_channel#6507]
I have the following two entries in Package Control

https://github.com/wbond/package_control_channel/blob/39e4795447bf495752c2aef926ded2164b6d9098/repository/j.json#L143-L164

Which are managed at two separate repos

https://github.com/JamieMason/Jasmine-Matchers-ES6-Snippets
https://github.com/JamieMason/Jasmine-Matchers-Snippets

I wondered if the JSON spec lets you describe packages which are managed within monorepos? I would like to move the above repos to https://github.com/JamieMason/Jasmine-Matchers under `packages/Jasmine-Matchers-Snippets` and `packages/Jasmine-Matchers-ES6-Snippets`.

A naive guess would be to change eg. `"details": "https://github.com/JamieMason/Jasmine-Matchers-ES6-Snippets"` to `"details": "https://github.com/JamieMason/Jasmine-Matchers/packages/Jasmine-Matchers-ES6-Snippets"` but I don't think that is likely to work as you'll be expecting the root of a git repo?

Thanks for your time.

**Comment by FichteFoll** [comment]
This is not possible (currently).

**Comment by evandrocoan** [comment]
@JamieMason, for this to be possible, would require support by the Package Control installer. This has already been requested to be implemented on:

1. https://github.com/wbond/package_control/issues/1230 [Feature Request] allow adding a Git Repository that contains multiple packages as root folders

After that improvement/feature to be implemented, you can use whatever structured they implement to accomplish this feature.
