### ISSUE TITLE
Changing git url 

### ISSUE THREAD

**Issue by stoivo** [wbond/package_control_channel#6714]
We would like to change the git url to our 
is it enough to change 
```
		{
			"name": "Elm Language Support",
			"details": "https://github.com/elm-community/Elm.tmLanguage",
			"labels": ["language syntax"],
			"previous_names": ["Elm Syntax Highlighting"],
			"releases": [
				{
					"sublime_text": "*",
					"tags": true
				}
			]
		},
```
TO 
```
		{
			"name": "Elm Language Support",
			"details": "https://github.com/elm-community/ElmLanguageSupport",
			"labels": ["language syntax"],
			"previous_names": ["Elm Syntax Highlighting"],
			"releases": [
				{
					"sublime_text": "*",
					"tags": true
				}
			]
		},
```

**Comment by sentience** [comment]
In particular, what is the recommended way to sync the change to our repository name with the change to the Package Control channel?

**Comment by FichteFoll** [comment]
I think that Github recently started redirecting the API for repository renames too, so the timing isn't as ciritical, i.e. you can rename the repo and then file the PR without having to worry about the package being missing. I suggest testing this locally, however.

Otherwise, depending on my activity with reviewing PRs, you may also wait for the rename after I merged the PR.

**Comment by evandrocoan** [comment]
Something very similar to this was already merged on:

1. https://github.com/wbond/package_control_channel/pull/6756 Elm Language Support repository change url

@stoivo Is this still unresolved?

**Comment by FichteFoll** [comment]
The question has been answered, so I'm closing. If you have any further problems related to this, feel free to add another comment.

**Comment by stoivo** [comment]
It is unresolved.

**Comment by evandrocoan** [comment]
> It is unresolved.

Then, can you open a pull request fixing the name?

**Comment by stoivo** [comment]
#6756 is that PR and it is merged

**Comment by evandrocoan** [comment]
So, it is resolved, instead of unresolved.

**Comment by stoivo** [comment]
Derp,  yes it. I don't know why I wrote `unresolved`.  🤦‍♂️
