### ISSUE TITLE
ERROR: No valid semver tags found

### ISSUE THREAD

**Issue by ErdemAkin** [wbond/package_control_channel#6716]
I want to install a package. 
The package I want to load is: https://github.com/ErdemAkin/Titan-Edge-Highlighter

I tested it as in the steps in the documentation and did not have any problems. I made pull request. But they wanted to fix that there was a mistake like this.

Packages added:
  - Titan Edge Highlighter

Processing package "Titan Edge Highlighter"
  - ERROR: No valid semver tags found at https://github.com/ErdemAkin/Titan-Edge-Highlighter/tags for the package "Titan Edge Highlighter".

**Comment by FichteFoll** [comment]
Looks fixed now. I'll take a look at the actual PR at another time, however.
