### ISSUE TITLE
JSX is missing from package control.

### ISSUE THREAD

**Issue by allanhortle** [wbond/package_control_channel#6751]
After [this pr](https://github.com/wbond/package_control_channel/pull/6709) was merged JSX went missing from package control: https://packagecontrol.io/packages/JSX

I may have misread the meaning of this comment: https://github.com/wbond/package_control_channel/pull/6709#issuecomment-344089432

I had checked out the old branch and pushed a tag called `st2-v2.0.2` which matched the old version just with `st2-` prepended.

I've now pushed `st2-v3.0.2` at that commit as per the comment.

Just looking for some clarity around this whole process. It seems pretty undocumented and hard for package devs to get right.

**Comment by FichteFoll** [comment]
You don't have a tag with `st2-v` prefixed here: https://github.com/allanhortle/JSX/tags

**Comment by allanhortle** [comment]
Oh dear. What a derp. I was running `git push --follow-tags` and just assuming it was working.
