### ISSUE TITLE
PhpDoc

### ISSUE THREAD

**Issue by chabinot** [wbond/package_control_channel#6823]
Hello,
I've installed PhpDoc on my Sublime Text 3 (bulid 3156). It seems that it does not work. When i tape               /** then tab, the result is
/**
 *
*/
and that's all, no generated comments on my function.
Please, tell me what to do ?
Regards

**Comment by gh640** [comment]
Hello, @chabinot .

This repository is for managing the channels for [Package Control](https://packagecontrol.io/). I believe it's better to ask the question for the PhpDoc package on [the PhpDoc issue queue](https://github.com/SublimeText/PhpDoc/issues) (though I'm not sure it's actively maintained...).
