### ISSUE TITLE
Preferences Editor and Edit Preferences

### ISSUE THREAD

**Issue by evandrocoan** [wbond/package_control_channel#6880]
While I have both of these packages installed, I can almost never tell which one is which, as their names is almost the same thing:

1. [https://packagecontrol.io/packages/Edit Preferences](https://packagecontrol.io/packages/Edit%20Preferences)
1. [https://packagecontrol.io/packages/Preferences Editor](https://packagecontrol.io/packages/Preferences%20Editor)

I would suggest renaming one of these packages, cc @klorenz and @sublimator

@klorenz, I had forked your package `Preferences Editor` on GitHub last year, renaming it to `Quick Settings` and had done some big refactoring on it: https://github.com/evandrocoan/QuickSettings/graphs/contributors

What do you think about it? Are you still maintaining the package and would you like to receive some big pull request, or I can submit to package control channel a pull request submitting my fork as a new package or replacing yours?

**Comment by braver** [comment]
After a package has been added, the window for us to have an opinion about package names has closed. If you want a package to be renamed, please open an issue on their repository, and then they can open a PR to do the rename if they agree.
