### ISSUE TITLE
Service + website is down 

### ISSUE THREAD

**Issue by noudadrichem** [wbond/package_control_channel#6883]
https://packagecontrol.io/

![image](https://user-images.githubusercontent.com/16288476/34938639-613b2bac-f9e9-11e7-86c5-a56e21f58db7.png)

![image](https://user-images.githubusercontent.com/16288476/34938670-851c5f32-f9e9-11e7-9c52-0e3ff97129a0.png)

**Comment by FichteFoll** [comment]
Back up now.
