### ISSUE TITLE
Published package marked as "MISSING" with InvalidCertificateException

### ISSUE THREAD

**Issue by mechatroner** [wbond/package_control_channel#6966]
Hello!
My rainbow_csv package currently has error status which says "MISSING" 
Here is a screenshot:
![image](https://user-images.githubusercontent.com/5349737/36625247-18b5a126-18ea-11e8-8e9f-691f88ad86c5.png)

I've searched for "InvalidCertificateException" error in this repository and found that it is also appears in some open pull requests. 
Please fix!

**Comment by FichteFoll** [comment]
https://github.com/wbond/package_control/issues/1334
