### ISSUE TITLE
Replacing LC-3 package for Sublime Text 3

### ISSUE THREAD

**Issue by Zenexer** [wbond/package_control_channel#6984]
There's an [existing package](https://github.com/mcgunslinger/Sublime-LC3) for LC-3 assembly in the repo, but it only offers very basic syntax highlighting via scopeless pattern matching, and it's designed for Sublime Text 2.  I made [another package](https://github.com/Zenexer/sublime-lc3) for LC-3 assembly with much more advanced syntax highlighting and even simple validation, but it only works with Sublime Text 3.  How should I go about adding mine to the repo?

**Comment by FichteFoll** [comment]
The usual procedure would be to replace the package with yours in a new PR and pinging the original author in that PR to ask for their consent. If they don't reply within 14 days, we consider them to be AWOL and merge.

Feel free to refer to this issue in the PR regarding an "official" statement about the procedure.

**Comment by FichteFoll** [comment]
Just to clarify, when ST3 wasn't stable, it might have been desireable to keep an old ST2 version of the syntax around, but I don't think this is necessary anymore. The usage percentage of ST2 builds is diminishingly small (about 2% according to the last PC numbers a few months ago).
