### ISSUE TITLE
Make a labelling pass through the PR backlog

### ISSUE THREAD

**Issue by tmelot2** [wbond/package_control_channel#7097]
From just looking at the PR listing, you can't really tell what is waiting on feedback and what needs to be reviewed. I can go through all the PRs and label things that are awaiting feedback as `feedback required` (which is what I assume that is used for). I could also put other labels on things. There are enough items in the queue to warrant some organization. What do you think?

**Comment by tmelot2** [comment]
Wasn't going to make any edits until someone said it was cool but just noticed that actually don't have permission to do it anyways, haha. I think it would be useful and shouldn't take too long. Happy to do it myself if I can get labelling permission. 

@Thom1729 has been very active with the reviews lately; do you think this would be useful?

**Comment by Thom1729** [comment]
I've gone through and labelled a bunch of PRs as stale. I'm hoping to get through the remainder of the backlog over the next couple of weeks, which should leave a manageable number of PRs to label.

**Comment by tmelot2** [comment]
Ah, got it. Yeah I could see the overhead of having to repeatedly make manual passes over 70+ PRs could get long and tiresome. Thom has been really killing reviews recently, and I hope to get some time to contribute more as well, so maybe once the list has been shaved down some we can reevaluate. Thanks for taking the time to chat about it!
