### ISSUE TITLE
Confusing names Word​Highlight versus Highlight​Words

### ISSUE THREAD

**Issue by evandrocoan** [wbond/package_control_channel#7341]
This problem is like having one of them named `Word​Highlight` and the other `Word ​Highlight` (with space on the name). I got both packages installed, and it is always hard to know which one I am using. 

The same as: 
1. https://github.com/wbond/package_control_channel/issues/6880 Preferences Editor and Edit Preferences

**Comment by braver** [comment]
Indeed, same as #6880, same reaction from me :)
