### ISSUE TITLE
Support github.io links

### ISSUE THREAD

**Issue by niosus** [wbond/package_control_channel#7361]
As in #7323 I have tried to move from using a github link as the web page for the package towards pointing people to the github pages link. It makes sense to me as the github pages link is more customizable and can provide more details in a better format to the users. However, as that PR was merged it made my package unavailable from the package control. It does not seem to be hard to support also the github pages links as the change difference is minimal. e.g.:
```diff
- "https://github.com/niosus/EasyClangComplete",
+ "https://niosus.github.io/EasyClangComplete/",
```

**Comment by FichteFoll** [comment]
That's what the `homepage` key is for. https://github.com/wbond/package_control/blob/db53090bd0920ca2c58ef27f0361a4d7b096df0e/example-repository.json#L90

**Comment by FichteFoll** [comment]
Also, since PC sources the homepage url from what you set as the url to your repo (next to the description), your github.io URL is already live, so I'm closing this.
