### ISSUE TITLE
Can't search my plugin

### ISSUE THREAD

**Issue by evercyan** [wbond/package_control_channel#7443]
Hi,

for my package "subryan"
here is the pull request record, https://github.com/wbond/package_control_channel/pull/7441
but I can't find it in repository/s.json and https://packagecontrol.io/channel_v3.json, also can't search it on https://packagecontrol.io

I don't know why~

thank you very much
ryan

**Comment by evercyan** [comment]
Maybe because I remove the package_control_channel which forked from this
Let me have a try again

**Comment by FichteFoll** [comment]
The pull request was closed by you before it was reviewed and merged, so it was never added.
