### ISSUE TITLE
New Packages?

### ISSUE THREAD

**Issue by zpreston123** [wbond/package_control_channel#7462]
Is there an issue with Package Control unable to release new packages?

Last one was released about a month ago.

Not sure if this is a manual or automated process.

**Comment by FichteFoll** [comment]
It's a manual progress and I'm currently preparing for exams, which doesn't exactly allow me to spend hours for reviewing. It's not a good feeling to see the number of notifications rise every day.

Maybe @Thom1729 could take a look, however?

**Comment by Thom1729** [comment]
Should be able to do a thorough pass this week.

**Comment by zpreston123** [comment]
Noticed new packages being released.  Thanks @Thom1729!

Closing issue.
