### ISSUE TITLE
Split sublime version more than once

### ISSUE THREAD

**Issue by michaelblyons** [wbond/package_control_channel#7464]
Is there a way to split releases by Sublime version more than once? Like this, but with 3+ entries?

https://github.com/wbond/package_control/blob/master/example-repository.json#L322-L338

For example, when `embed` came out as a keyword on the Dev channel, was there a way for developers supporting ST2 to also support _both_ pre-`embed` and post-`embed` ST3s while they waited for a stable ST3 release with `embed`?

**Comment by FichteFoll** [comment]
You may use a range selector like `3100 - 3189`.
