### ISSUE TITLE
Package EditorConfig not found.

### ISSUE THREAD

**Issue by sptndc** [wbond/package_control_channel#7706]
Why can't I find the Package EditorConfig in Sublime Text Build Dev 3210?

**Comment by FichteFoll** [comment]
[Seems to be there just fine](https://packagecontrol.io/packages/EditorConfig). Do you already have it installed but disabled?

**Comment by sptndc** [comment]
I have not installed it, let alone disabled it. Because I just fresh install Sublime Text.

**Comment by braver** [comment]
It's like that sometimes 🤷🏻‍♂️ There have been hiccups at times, but the package is listed if you try to install it now.
