### ISSUE TITLE
Package is not updated

### ISSUE THREAD

**Issue by daniele-niero** [wbond/package_control_channel#7807]
Hi,

I've noticed this problem happened in the past for other users/developers.   
Unfortunately this is happening again for me.

My package repository is https://bitbucket.org/daniele-niero/sublimeprojectenvironment

In the last two/three weeks I've updated to version 1.0.11 (from 1.0.10) and that was successful. 
Yesterday I've updated to Version 2.0.0, but that was never been seen by PackageControl.  
Not only, even if PackageControl still showing version 1.0.11, the readme is not picked up anymore.

Check the page [https://packagecontrol.io/packages/Project Environment](https://packagecontrol.io/packages/Project%20Environment)

The previous issues were caused by bugs in the crawler, but I suspect this time there is something wrong with my repository, although, I can't figure out what.

Edit:  
And now I've noticed that Package Control doesn't see my Package anymore. But Still, I can't figure out why

**Comment by FichteFoll** [comment]
Your tag looks correct and it appears that PC has correctly picked up the previous update. I can't tell from here what's wrong exatly, but the readme not being picked up could be a bug in https://github.com/wbond/package_control.

**Comment by daniele-niero** [comment]
Everything was working nice until version 1.0.11, after that all went kaboom...

**Comment by wbond** [comment]
This has been fixed now

**Comment by daniele-niero** [comment]
Many thanks!
