### ISSUE TITLE
packagecontrol-bot doesn't warn about .sublime-syntax build requirement when taking over

### ISSUE THREAD

**Issue by ISSOtm** [wbond/package_control_channel#7840]
That's a mouthful.

In #7819, I took over the [Bison](https://packagecontrol.io/packages/Bison) package, and put the required build at 3084:

https://github.com/wbond/package_control_channel/blob/d82afad95a442e17cd27823f589470445da8c9ea/repository/b.json#L817

But then when I did the same for #7839, [I was rightfully warned](https://github.com/wbond/package_control_channel/pull/7839#pullrequestreview-365002687). Shouldn't the bot also report that warning when taking over packages? (There's possibly more to this, I don't know.)

**Comment by FichteFoll** [comment]
No, because modifications to existing can be so versatile, the bot doesn't check them at all and only checks added packages.

**Comment by ISSOtm** [comment]
That makes sense, but shouldn't the resulting package be analyzed for errors like these?

**Comment by FichteFoll** [comment]
Probably yes, since the errors are specific enough to prevent false positives, which are disrupting to the review flow and those cases that require more careful consideration or human discretion are warnings.

FWIW, you can run the checker manually for your packags, if desired: https://github.com/packagecontrol/st_package_reviewer

**Comment by braver** [comment]
Any package can change in a way that violates things like the version requirements and any other tests once added. We don't run continuous checks on packages. The initial review starts a package off on the right path, but the responsibility completely resides with the package author.
