### ISSUE TITLE
Cant install new package

### ISSUE THREAD

**Issue by raphaelquintao** [wbond/package_control_channel#8224]
I cant install my new approved package [QColor](https://packagecontrol.io/packages/QColor)
But i can install that one: [Open DOI](https://packagecontrol.io/packages/Open%20DOI) which is newer than mine.

Whats happening?

**Comment by rwols** [comment]
Package Control does not show packages you already have in either `$DATA/Installed Packages` or `$DATA/Packages`.

**Comment by raphaelquintao** [comment]
I was trying on a clean installation of sublime.
But now it appears.
