### ISSUE TITLE
gitlab package not appearing on Package Control

### ISSUE THREAD

**Issue by Jiehong** [wbond/package_control_channel#8249]
Hi,

https://github.com/wbond/package_control_channel/pull/8245 was merged, but it never shows up on Package Control.

In the list of commits, we can see that it was merged after "Mint Lang", and before "Hammock Color Scheme":

![image](https://user-images.githubusercontent.com/1061229/114836330-d2c8cc80-9dd2-11eb-8739-ff60523a1ef4.png)

While on Package Control, the list of new packages correctly show Mint and Hammock, but without "Jq", even though it should be in between those, time-wise. Searching for it also does not show it:

![image](https://user-images.githubusercontent.com/1061229/114836454-f7bd3f80-9dd2-11eb-8031-9159bd2f0222.png)

**Comment by TheSecEng** [comment]
@Jiehong Just want to update that this is being investigated. In the mean time, I did test this by adding the Gitlab URL as a "repository" and confirmed on the plugin side it is working. Appears to be a bug on the packagecontrol.io website.

**Comment by Jiehong** [comment]
@TheSecEng Is there any news? Should I open an issue on https://github.com/wbond/packagecontrol.io/issues instead then?

**Comment by braver** [comment]
Indeed, this isn't a channel issue, but internally to package control. You can continue to track this [there](https://github.com/wbond/packagecontrol.io/issues/138)
