### ISSUE TITLE
Fixes #8263 > Oh, it's a color scheme, not a theme. In that case, add a "color scheme" label (not just in the name), so it's listed here: https://packagecontrol.io/browse/labels/color%20scheme

### ISSUE THREAD

**Issue by luxelego** [wbond/package_control_channel#8267]
> Oh, it's a color scheme, not a theme. In that case, add a "color scheme" label (not just in the name), so it's listed here: https://packagecontrol.io/browse/labels/color%20scheme

Yes, I create label "color scheme" in Issue.

_Originally posted by @luxelego in https://github.com/wbond/package_control_channel/issues/8263#issuecomment-832711338_

**Comment by braver** [comment]
Not sure why this is here?
