### ISSUE TITLE
Documentation: "Repository" means different things in different contexts

### ISSUE THREAD

**Issue by haferburg** [wbond/package_control_channel#8364]
https://packagecontrol.io/docs/channels_and_repositories

> Repositories are JSON files hosted on a URL

https://packagecontrol.io/docs/usage

> Add Repository
>    Add a repository that is not included in the default channel. This allows users to install and automatically update packages from GitHub and BitBucket. To add a package hosted on GitHub, enter the URL in the form https://github.com/username/repo

-----

So for a dev you define a repository as a JSON file, but the "Add repository" command uses the term quite differently. You can't use "Add repository" to add a repository JSON file. And the "Add repository" command doesn't seem to do any verification when you use it.

In my opinion the word repository is not a good choice for that JSON file, because it's not so much a container, but just lists packages. Maybe "package list" would be more accurate.

> A package list is a JSON file hosted on a URL. It contains a list of one or more packages. See example-package-list.json for the format. The JSON structure allows for specifying platforms (Windows, OS X, Linux), compatible versions of Sublime Text, labels, URLs and more. The default channel includes a number of third-party package lists, but also a single, centralized package list for developers who are using GitHub or BitBucket tag-based releases. This way a package only ever needs to be added to the package list once and almost all further updates to the package can be performed via the GitHub or BitBucket user interfaces. 

What do you think?

**Comment by braver** [comment]
Sorry about letting this sit here for so long, we tend to be focused on handling the pull requests around here… the issues are typically only about tools like the tests we run. You’re right, this issue should be opened at https://github.com/wbond/package_control instead.
