### ISSUE TITLE
Package not updated

### ISSUE THREAD

**Issue by mortalis13** [wbond/package_control_channel#8477]
Hi.
My package is not updated since the last week.
https://packagecontrol.io/packages/Norber%20Theme

The latest version showed is 1.0.6.
But the latest git tag/commit is 1.4.

Could you check it?
Thanks.

**Comment by rchl** [comment]
I think that PC requires 3 components in the version (1.4.0).

**Comment by FichteFoll** [comment]
That is correct, your tag must be a semantic version with 3 numeric components.
