### ISSUE TITLE
RFC: `CustomStatusMessage` plugin

### ISSUE THREAD

**Issue by jfcherng** [wbond/package_control_channel#8625]
As per @jrappen's suggestion in https://discord.com/channels/280102180189634562/280157209017450507/1031656498943758466, I create this issue as a request for comment for https://packagecontrol.io/packages/CustomStatusMessage (https://github.com/jfcherng-sublime/ST-CustomStatusMessage).

Unfortunately, it has been released on Package Control before I create this issue here. I don't know what's the proper procedure to take it down now.

## Why creating that plugin?

To disable the built-in Line/Column message in the status bar and make it easier to show a custom format of Line/Column message.

Resovles 

- https://github.com/sublimehq/sublime_text/issues/2550
- https://github.com/sublimehq/sublime_text/issues/3377

**Comment by braver** [comment]
Packages added to custom repositories don’t need to be announced here. If we give you the power to publish packages, we’re not going to still want to be involved in you doing so. What’s the point in that? And who would have time for all of that anyway?
