### ISSUE TITLE
Please explain gitattributes

### ISSUE THREAD

**Issue by sporto** [wbond/package_control_channel#8792]
When submitting a PR one of the TODO is

> I use [.gitattributes](https://www.git-scm.com/docs/gitattributes#_export_ignore) to exclude files from the package: images, test files, sublime-project/workspace.

It is unclear how are we meant to use this to exclude files.
Please add some documentation or an example.
Probably here https://packagecontrol.io/docs/submitting_a_package

Thanks

**Comment by braver** [comment]
In general [documentation on the website](https://github.com/wbond/packagecontrol.io/tree/master/app/html/docs) is definitely in need of an update and clarification in various areas. This repo is only about the channel itself, managing the dataset for it and reviewing additions. Typically maintainers here don't have access to the repo that manages the website. As such, there is only so much we can do in terms of documentation. 

So, your request should be filed at https://github.com/wbond/packagecontrol.io. You'll notice there isn't a lot of actual activity on that repo, but we're already trying to work out some changes with the owner of the package control repos to up the level of maintenance across the board.

**Comment by sporto** [comment]
Thanks

**Comment by FichteFoll** [comment]
It appears the question has been answered,
