### ISSUE TITLE
Update package issue

### ISSUE THREAD

**Issue by yaroslavyaroslav** [wbond/package_control_channel#8799]
I'm maintaining this [package](https://packagecontrol.io/packages/OpenAI%20completion).

The version in package_control_channel is 2.1.2, while the latest tag @ the repo is 2.1.3, and even though this one was pushed just yet, there was equal one which was not fetched completely. Why?

**Comment by yaroslavyaroslav** [comment]
It worked, I guess you've changed worked schedule somehow 🤷🏻‍♂️

**Comment by FichteFoll** [comment]
There were some issues with the package update that have been fixed in the past days, yes.
