### ISSUE TITLE
curl fails in CI

### ISSUE THREAD

**Issue by KenyC** [wbond/package_control_channel#8901]
I submitted my package as PR #8900 and some of the tests failed (cf [here](https://github.com/wbond/package_control_channel/pull/8900)). It is not clear why it failed but it *looks* like it's unrelated to my package (failed curl command). 

What should I do? (I don't know the first thing about CI so forgive me if there's a naive "just run the checks again" option that I have missed)

**Comment by braver** [comment]
see https://github.com/wbond/package_control_channel/pull/8900#issuecomment-2035303991
